@echo off
echo Starting Pet Consultation Platform...
echo.
echo Starting backend server...
start "Backend Server" cmd /k "cd backend && npm run dev"
timeout /t 3 /nobreak > nul
echo.
echo Starting frontend development server...
start "Frontend Server" cmd /k "cd pet-consultation && npm run dev"
echo.
echo Both servers are starting...
echo Backend will be available at: http://localhost:3000
echo Frontend will be available at: http://localhost:5173
echo.
echo Press any key to exit...
pause > nul